### ISSUE TITLE
License for Infinite Ajax Scroll plugin

### ISSUE THREAD

**Issue by ihor-sviziev** [Strategery-Inc/Magento2-InfiniteScroll#27] opened 2018-06-09 07:34 UTC
I see that current magento 2 module using jquery-ias plugin, that in head contains information that for commercial use we need to buy license:
https://github.com/Strategery-Inc/Magento2-InfiniteScroll/blob/master/view/frontend/web/js/jquery-ias.min.js#L6

Could you explain, should we buy license for using this extension on Magento 2 in commercial projects?

**Comment by gsomoza** [comment] 2018-06-11 07:31
The license guidelines for Infinite Ajax Scroll are here: https://infiniteajaxscroll.com/docs/license.html

We're not lawyers, so we can't offer you advice about your specific situation – you should do that research yourself based on what type of company you own, what you're doing with the source code, etc. 

With that being said, we think there are two main reasons why users of this plugin may not have to buy a license:

1. We (the original developers of this plugin) have bought an "Unlimited" license for IAS. We believe this gives us the right to bundle the library when we distribute this plugin to 3rd parties. We just happen to choose to NOT to actually sell this plugin (or sell it for $0). This probably means that the library should only be used for the purposes of this specific plugin: you might have to buy a license of your own if you intend to use the library for another purpose.

2. This plugin is Open Source, as is Magento. The license for IAS states (emphasis mine): 
> For non-commercial, personal, or **open source projects** and applications, you may use Infinite AJAX Scroll under the terms of the MIT License. You may use Infinite AJAX Scroll for free.

In my opinion this second item clearly means that we (the developers of this open source plugin) are allowed to use IAS to the full extent of the MIT terms. Those terms state (again, emphasis mine):

> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to **use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software** (...)

Which, again in our opinion, means all users of our plugin would automatically be granted a free copy of IAS licensed under MIT.

I hope this helps clarify the license situation. To us it's quite clear, but you'll have to arrive at your own conclusions since we can't offer specific legal advice to you and we don't offer any kind of warranties over this code-base.

Thanks for opening the ticket. I'll close it now because it's not a bug, but we can continue the discussion anyways if you have any more questions or would like to follow-up in any way.

**Closed as completed by gsomoza** 2018-06-11 07:31 UTC

**Comment by ihor-sviziev** [comment] 2018-06-11 07:57
@gsomoza  thank you for reply, but it's actually still not clear. So I created https://github.com/webcreate/infinite-ajax-scroll/issues/319 for response from plugin developers

**Comment by gsomoza** [comment] 2018-06-11 08:04
Sure, they should be able to give you a more final answer.

**Comment by ihor-sviziev** [comment] 2018-06-11 10:36
@gsomoza we need to have this license. Details: https://github.com/webcreate/infinite-ajax-scroll/issues/319#issuecomment-396187650

**Comment by gsomoza** [comment] 2018-06-11 11:06
Thanks for the update. I'm following that issue to see what comes out of it so we can update our plugin (or docs) if necessary.
